model_target: mod_fork_custom.mod_model_fork_custom.MAE_ViT_2_T
seed: 2022
batch_size: 128
max_device_batch_size: 256
base_learning_rate: 1.0e-3
weight_decay: 0.05
total_epoch: 100
warmup_epoch: 5
save_model_path: save_model_path/mae/mod_custom
save_model_name: custom_mod_tiny
mixed_precision: 'fp16'
