model_target: baseline.model.MAE_ViT_2_T
seed: 2022
batch_size: 4096
max_device_batch_size: 1024
base_learning_rate: 1.5e-4
weight_decay: 0.05
mask_ratio: 0.75
total_epoch: 8000
warmup_epoch: 800
loss: l2
mixed_precision: 'fp16'
save_model_path: save_model_path/mae/baseline_aux
save_model_name: baseline_aux09_tiny
use_aux_dataset: true
unsup_fraction: 0.9
aux_data_filename: /home/jtitor/Downloads/1m.npz
optimizer:
  target: torch.optim.AdamW
  configs:
    blr: 1.0e-4
    betas: [0.9, 0.999]
    weight_decay: 0.05


