model_target: mod_fork_every2.mod_model_fork_every2.MAE_ViT_2_T
seed: 2022
batch_size: 128
max_device_batch_size: 256
base_learning_rate: 1.0e-3
weight_decay: 0.05
total_epoch: 100
warmup_epoch: 5
pretrained_model_path: None
save_model_path: save_model_path/mae/mod_every2
save_model_name: mod_every2_tiny
mixed_precision: 'fp16'
