model_target: mod_fork_every2.mod_model_fork_every2.MAE_ViT_2_T
seed: 2022
batch_size: 4096
max_device_batch_size: 1024
base_learning_rate: 1.5e-4
weight_decay: 0.05
mask_ratio: 0.75
total_epoch: 2000
warmup_epoch: 200
loss: l2
mixed_precision: 'fp16'
save_model_path: save_model_path/mae/mod_every2
save_model_name: mod_every2_tiny
